apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "seleniumhub", "namespace": "", "kind": "DeploymentConfig"}]'
    name: selenium-hub-pipeline
  spec:
    source:
      git:
        ref: pipeline
        uri: https://github.com/Midovich22951/seleniumgrid.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
