apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "seleniumgrid", "namespace": "selenium", "kind": "DeploymentConfig"}]'
    name: seleniumgrid-pipeline
  spec:
    source:
      git:
        ref: pipeline
        uri: https://github.com/Midovich22951/seleniumgrid.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: azertyuu
      type: Generic